import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth } from '../lib/auth'

const Home: NextPage = () => {
  const auth = useAuth()
  console.log(auth)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="py-4 text-3xl font-bold underline">Hello world!</h1>

      {auth?.user != null ? (
        <button onClick={() => auth!.signout()}>Sign Out</button>
      ) : (
        <button onClick={() => auth!.signinWithGithub()}>
          Sign in with Github
        </button>
      )}
      {auth?.user !== null && (
        <>
          <div>{auth!.user?.displayName}</div>
          <div>{auth!.user?.email}</div>
        </>
      )}
    </div>
  )
}

export default Home
