import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth } from '../lib/auth'

const Home: NextPage = () => {
  const auth = useAuth()
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="py-4 text-3xl font-bold underline">Hello world!</h1>
      <button onClick={() => auth.signinWithGithub()}>
        Sign in with Github
      </button>
      <div>{auth?.user?.email}</div>
    </div>
  )
}

export default Home
